# Site settings
title: Caok
email: caok1231@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Caok's personal website published personal blog articles and study notes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://caok1231.com" # the base hostname & protocol for your site
twitter_username: caok1231
github_username:  caok

# Build settings
markdown: kramdown
